### ISSUE TITLE
[Issue] Unable to ssh blank with no error logs 

### ISSUE THREAD

**Issue by niaosuan** [gnmyt/Nexterm#140]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

Able to issue ssh via cli from the docker container however when trying from Nexterm session blank page. No error via 'docker logs {Container_ID}'.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by mastankiewicz** [comment]
The same here. SSH no errors. 

RDP error: 

Error in guacamoleProxy: TypeError: Cannot read properties of undefined (reading 'on')

    at module.exports (/app/server/controllers/guacamoleProxy.js:9:12)

    at module.exports (/app/server/middlewares/guacamole.js:10:5)

An error occurred: Cannot read properties of undefined (reading 'close')

**Comment by breakersun** [comment]
It doesn't work at all with a session from a container:
![image](https://github.com/user-attachments/assets/a38f7876-fbfe-433a-9765-094dfa70fb3b)

**Comment by breakersun** [comment]
> It doesn't work at all with a session from a container: ![image](https://private-user-images.githubusercontent.com/6301217/385167283-a38f7876-fbfe-433a-9765-094dfa70fb3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDcxNzgsIm5iZiI6MTczMTQwNjg3OCwicGF0aCI6Ii82MzAxMjE3LzM4NTE2NzI4My1hMzhmNzg3Ni1mYmZlLTQzM2EtOTc2NS0wOTRkZmE3MGZiM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTAyMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE3MWEyYjI3M2M1MDRlNTExMmMxYTZkNDNiY2QyNjNhYzFkYzIyNzNmNTE4MjAzYTJjMGQ3N2Y4M2Q0ZWM5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ui4FKFhaaNuu_GIEKxmByPbZnZjfO_qe43MHikoaOT0)

Turns out I have to set correct user and passwords to open the ssh session. If I leave the passwords as blank it will never open ssh session and report no errors.

**Comment by boka89** [comment]
It would be good, if you could start a ssh session, and the window would ask for the username and password

**Comment by charredchar** [comment]
This would be useful for Windows as well so you don't need a new "server" connection for each user and you also don't need to save logins within Nexterm. Though with RDP you need to provide it to start the connection so maybe you could have a popup on connection asking for username and/or password if one isn't saved.
